name: Build and Publish

on:
  push:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: python -m pip install hatch
    - name: Build wheel
      run: hatch -v build -t wheel:standard
    - name: Publish
      run: |
        echo 'do something'
